# Change these first
owner: ichengchao # Your GitHub organization or username, where this repository lives
repo: myuptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: chengchao.name
    url: https://www.chengchao.name
  - name: chengchao blog
    url: https://blog.chengchao.name
  - name: chengchao site
    url: https://chengchao.name/springrun/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /myuptime
  logoUrl: https://ichengchao.oss-cn-hangzhou.aliyuncs.com/static/image/login_logo.png
  name: ichengchao
  introTitle: "**ichengchao** status"
  introMessage: "[**chengchao.name**](https://www.chengchao.name)"
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.chengchao.name
    - title: Blog
      href: https://blog.chengchao.name

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
